//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonusMvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblpersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpersonel()
        {
            this.tblsatislar = new HashSet<tblsatislar>();
        }
    
        public int id { get; set; }
        public Nullable<int> departmanId { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<short> maas { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public bool cinsiyet { get; set; }
        public bool evlilikdurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatislar> tblsatislar { get; set; }
        public virtual tbldepartman tbldepartman { get; set; }
    }
}
